// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: billingpb/billingpb.proto

package billingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BillingAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillingAccount) Reset() {
	*x = BillingAccount{}
	mi := &file_billingpb_billingpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingAccount) ProtoMessage() {}

func (x *BillingAccount) ProtoReflect() protoreflect.Message {
	mi := &file_billingpb_billingpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingAccount.ProtoReflect.Descriptor instead.
func (*BillingAccount) Descriptor() ([]byte, []int) {
	return file_billingpb_billingpb_proto_rawDescGZIP(), []int{0}
}

func (x *BillingAccount) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BillingAccount) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateBillingAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBillingAccountRequest) Reset() {
	*x = CreateBillingAccountRequest{}
	mi := &file_billingpb_billingpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBillingAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillingAccountRequest) ProtoMessage() {}

func (x *CreateBillingAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billingpb_billingpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillingAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateBillingAccountRequest) Descriptor() ([]byte, []int) {
	return file_billingpb_billingpb_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBillingAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateBillingAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBillingAccountResponse) Reset() {
	*x = CreateBillingAccountResponse{}
	mi := &file_billingpb_billingpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBillingAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillingAccountResponse) ProtoMessage() {}

func (x *CreateBillingAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billingpb_billingpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillingAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateBillingAccountResponse) Descriptor() ([]byte, []int) {
	return file_billingpb_billingpb_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBillingAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetBillingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingRequest) Reset() {
	*x = GetBillingRequest{}
	mi := &file_billingpb_billingpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingRequest) ProtoMessage() {}

func (x *GetBillingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billingpb_billingpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingRequest.ProtoReflect.Descriptor instead.
func (*GetBillingRequest) Descriptor() ([]byte, []int) {
	return file_billingpb_billingpb_proto_rawDescGZIP(), []int{3}
}

func (x *GetBillingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBillingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingResponse) Reset() {
	*x = GetBillingResponse{}
	mi := &file_billingpb_billingpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingResponse) ProtoMessage() {}

func (x *GetBillingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billingpb_billingpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingResponse.ProtoReflect.Descriptor instead.
func (*GetBillingResponse) Descriptor() ([]byte, []int) {
	return file_billingpb_billingpb_proto_rawDescGZIP(), []int{4}
}

func (x *GetBillingResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type UpdateBillingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBillingRequest) Reset() {
	*x = UpdateBillingRequest{}
	mi := &file_billingpb_billingpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBillingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBillingRequest) ProtoMessage() {}

func (x *UpdateBillingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billingpb_billingpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBillingRequest.ProtoReflect.Descriptor instead.
func (*UpdateBillingRequest) Descriptor() ([]byte, []int) {
	return file_billingpb_billingpb_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBillingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateBillingRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type UpdateBillingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBillingResponse) Reset() {
	*x = UpdateBillingResponse{}
	mi := &file_billingpb_billingpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBillingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBillingResponse) ProtoMessage() {}

func (x *UpdateBillingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billingpb_billingpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBillingResponse.ProtoReflect.Descriptor instead.
func (*UpdateBillingResponse) Descriptor() ([]byte, []int) {
	return file_billingpb_billingpb_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBillingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_billingpb_billingpb_proto protoreflect.FileDescriptor

const file_billingpb_billingpb_proto_rawDesc = "" +
	"\n" +
	"\x19billingpb/billingpb.proto\x12\tbillingpb\"A\n" +
	"\x0eBillingAccount\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"6\n" +
	"\x1bCreateBillingAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x1cCreateBillingAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x11GetBillingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\",\n" +
	"\x12GetBillingResponse\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\"G\n" +
	"\x14UpdateBillingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"1\n" +
	"\x15UpdateBillingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x98\x02\n" +
	"\x0eBillingService\x12g\n" +
	"\x14CreateBillingAccount\x12&.billingpb.CreateBillingAccountRequest\x1a'.billingpb.CreateBillingAccountResponse\x12I\n" +
	"\n" +
	"GetBilling\x12\x1c.billingpb.GetBillingRequest\x1a\x1d.billingpb.GetBillingResponse\x12R\n" +
	"\rUpdateBilling\x12\x1f.billingpb.UpdateBillingRequest\x1a .billingpb.UpdateBillingResponseB\rZ\v./billingpbb\x06proto3"

var (
	file_billingpb_billingpb_proto_rawDescOnce sync.Once
	file_billingpb_billingpb_proto_rawDescData []byte
)

func file_billingpb_billingpb_proto_rawDescGZIP() []byte {
	file_billingpb_billingpb_proto_rawDescOnce.Do(func() {
		file_billingpb_billingpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billingpb_billingpb_proto_rawDesc), len(file_billingpb_billingpb_proto_rawDesc)))
	})
	return file_billingpb_billingpb_proto_rawDescData
}

var file_billingpb_billingpb_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_billingpb_billingpb_proto_goTypes = []any{
	(*BillingAccount)(nil),               // 0: billingpb.BillingAccount
	(*CreateBillingAccountRequest)(nil),  // 1: billingpb.CreateBillingAccountRequest
	(*CreateBillingAccountResponse)(nil), // 2: billingpb.CreateBillingAccountResponse
	(*GetBillingRequest)(nil),            // 3: billingpb.GetBillingRequest
	(*GetBillingResponse)(nil),           // 4: billingpb.GetBillingResponse
	(*UpdateBillingRequest)(nil),         // 5: billingpb.UpdateBillingRequest
	(*UpdateBillingResponse)(nil),        // 6: billingpb.UpdateBillingResponse
}
var file_billingpb_billingpb_proto_depIdxs = []int32{
	1, // 0: billingpb.BillingService.CreateBillingAccount:input_type -> billingpb.CreateBillingAccountRequest
	3, // 1: billingpb.BillingService.GetBilling:input_type -> billingpb.GetBillingRequest
	5, // 2: billingpb.BillingService.UpdateBilling:input_type -> billingpb.UpdateBillingRequest
	2, // 3: billingpb.BillingService.CreateBillingAccount:output_type -> billingpb.CreateBillingAccountResponse
	4, // 4: billingpb.BillingService.GetBilling:output_type -> billingpb.GetBillingResponse
	6, // 5: billingpb.BillingService.UpdateBilling:output_type -> billingpb.UpdateBillingResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_billingpb_billingpb_proto_init() }
func file_billingpb_billingpb_proto_init() {
	if File_billingpb_billingpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billingpb_billingpb_proto_rawDesc), len(file_billingpb_billingpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billingpb_billingpb_proto_goTypes,
		DependencyIndexes: file_billingpb_billingpb_proto_depIdxs,
		MessageInfos:      file_billingpb_billingpb_proto_msgTypes,
	}.Build()
	File_billingpb_billingpb_proto = out.File
	file_billingpb_billingpb_proto_goTypes = nil
	file_billingpb_billingpb_proto_depIdxs = nil
}
